name: Generate requirements
on:
  push:
    branches:
      - master

jobs:
  generate:
    name: Generate requirements.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Run generate requirements.txt
        run: pipenv lock -r > requirements.txt
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          commit_message: Auto Generate requirements.txt
          file_pattern: requirements.txt
          skip_dirty_check: false
